# Generated by Django 4.2.5 on 2023-09-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_cv_display_order_cv_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
