# Generated by Django 4.2.5 on 2023-09-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_alter_cv_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
