# Generated by Django 4.2.5 on 2023-09-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmessage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
